### ISSUE TITLE
C++ WPILib Deploy sometimes does not show up

### ISSUE THREAD

**Issue by 333fred** [wpilibsuite/EclipsePlugins#16]
When in the Java perspective, the deploy command does not show up for C++. The reverse is not true: Java programs do not have this problem in the C++ perspective.

**Comment by Kevin-OConnor** [comment]
Fairly certain this was done on purpose. I think because the C++ plugin crashes if that menu is (loaded? run?) in the Java perspective and prevents the C++ Deploy menu items from showing up in either perspective until you restart Eclipse. I recall not being able to figure out how to fix that actual problem, so the workaround was to not show them outside the C++ perspective.

**Comment by Kevin-OConnor** [comment]
Found a different fix for this that allows it to show up in the Java perspective
