### ISSUE TITLE
Should provide location for installing source and javadoc jars

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/EclipsePlugins#90]
There should be a location (probably user\java\sourced and javadoc) where vendors can install source and javadoc jars, and variables set up to connect them to the library jar. Could probably assume the same extensions as vendor-template uses (-sources and -javadoc).

**Comment by Javaru** [comment]
I personally would prefer to be able to put source and javadoc JARs in the same directory `${userLibs.dir}` because  I use IntelliJ IDEA and it automatically detects sources and javadoc JARs in a lib directory. But putting them there causes all the sources and javadoc to be bundled into the `FRCUserProgram.jar`.

**This issue can be solved by a simple 1 line change** to the Ant build.xml file. In the `compile` target, change line 73 from this:
```
<fileset dir="${userLibs.dir}" includes="*.jar" />
```
to exclude sources and javadoc JARs like this:
```
<fileset dir="${userLibs.dir}" includes="*.jar" excludes="*-sources.jar,*-javadoc.jar" />
```
We are manually making that edit now. But it would be nice for this to be a permanent change (so we don't have to redo it when wpilib tools are updated) since, as the OP comments, having *-sources and *-javadoc JARs for libraries is a pretty standard practice.
